[package]
name = "vault-sync"
version = "0.2.0"
authors = ["Pavel Chekin <pbchekin@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
ctrlc = { version = "3.1.8", features = ["termination"] }
hashicorp_vault = "2.0.1"
log = "0.4.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.62"
serde_yaml = "0.8.17"
simplelog = "0.9.0"
