apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-sync.fullname" . }}
  labels:
    {{- include "vault-sync.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secrets | nindent 2 }}
